plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

title: ryanjames.dev
description: >-
  A personal blog by Ryan James where he collects his thoughts and learnings on Microsoft Dynamics 365, 
  PowerApps, Common Data Service, Azure, ASP.NET Core or what ever else he's into.
url: https://ryanjames.dev
author: Ryan James

twitter: 
  username: WhinyRyanie
  card: summary

facebooK:
  publisher: ryanmichaeljames

social:
  name: Ryan James
  links:
    - https://twitter.com/WhinyRyanie
    - https://www.facebook.com/ryanmichaeljames
    - https://www.linkedin.com/in/ryanmj
    - https://github.com/ryanmichaeljames

github:
  username: ryanmichaeljames
  userid: 16380903

linkedin:
  username: ryanmj

stackoverflow:
  username: ryan-james
  userid: "2501476"

baseurl: # the subpath of your site, e.g. /blog
permalink: /:categories/:year/:month/:day/:title/

timezone: Pacific/Auckland
lang: en_NZ

google_site_verification: soYMbME2lXgzvCVpWnsgzOTrObQ7UrvS-biBEJogxCM
google_analytics: UA-146448575-1

paginate: 4
paginate_path: "/blog/page:num/"

disqus:
  shortname: ryanjames-dev

sass:
  sass_dir: assets/css
