plugins:
  - jekyll-seo-tag
  - jekyll-paginate

# Jekyll site configuration
author: Ryan James
title: ryanjames.dev
email: 
description: >-
  A personal blog by Ryan James where he collects his thoughts and learnings on Microsoft Dynamics 365, 
  PowerApps, Common Data Service, Azure, ASP.NET Core or what ever else he's into.
baseurl: # the subpath of your site, e.g. /blog
url: https://ryanjames.dev # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:categories/:title/ #/:categories/:year/:month/:day/:title/
timezone: Pacific/Auckland
locale: en_NZ

# Social
twitter_username: WhinyRyanie
github_username:  ryanmichaeljames
github_userid: 16380903
linkedin_username: ryanmj

# Analytics
google_analytics: UA-146448575-1

# Build settings
sass:
  sass_dir: assets/css



# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
