plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

title: ryanjames.dev
description: >-
  A personal blog by Ryan James where he collects his thoughts and learnings on Microsoft Dynamics 365, 
  PowerApps, Common Data Service, Azure, ASP.NET Core or what ever else he's into.
url: https://ryanjames.dev
author: Ryan James

twitter: 
  username: WhinyRyanie
  card: summary

facebooK:
  publisher: ryanmichaeljames

social:
  name: Ryan James
  links:
    - https://twitter.com/WhinyRyanie
    - https://www.facebook.com/ryanmichaeljames
    - https://www.linkedin.com/in/ryanmj
    - https://github.com/ryanmichaeljames

github:
  username: ryanmichaeljames
  userid: 16380903

linkedin:
  username: ryanmj

baseurl: # the subpath of your site, e.g. /blog
permalink: /:categories/:title/ #/:categories/:year/:month/:day/:title/

timezone: Pacific/Auckland
lang: en_NZ

google_site_verification: soYMbME2lXgzvCVpWnsgzOTrObQ7UrvS-biBEJogxCM
google_analytics: UA-146448575-1

# Build settings
sass:
  sass_dir: assets/css



# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
